name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Prepare CI env (set safe defaults if secrets missing)
        env:
          ALPACA_API_KEY: ${{ secrets.ALPACA_API_KEY }}
          ALPACA_SECRET_KEY: ${{ secrets.ALPACA_SECRET_KEY }}
          ALPACA_BASE_URL: ${{ secrets.ALPACA_BASE_URL }}
        run: |
          ALPACA_API_KEY="${ALPACA_API_KEY:-ci}"
          ALPACA_SECRET_KEY="${ALPACA_SECRET_KEY:-ci}"
          ALPACA_BASE_URL="${ALPACA_BASE_URL:-https://paper-api.alpaca.markets}"
          echo "ALPACA_API_KEY=$ALPACA_API_KEY" >> $GITHUB_ENV
          echo "ALPACA_SECRET_KEY=$ALPACA_SECRET_KEY" >> $GITHUB_ENV
          echo "ALPACA_BASE_URL=$ALPACA_BASE_URL" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install alpaca-py python-dotenv pytest pytest-cov; fi

      - name: Run tests with coverage
        run: |
          . .venv/bin/activate
          pytest -q --cov=paper_trading --cov-report=term --cov-report=xml --cov-report=html

      - name: Upload coverage HTML artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-html
          path: htmlcov

      # - name: Upload coverage to Codecov (optional)
      #   if: ${{ secrets.CODECOV_TOKEN != '' }}
      #   uses: codecov/codecov-action@v4
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml